runtime: python311
instance_class: F4

env_variables:
  PYTHONPATH: /app

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 0
  max_instances: 10
  target_throughput_utilization: 0.6

resources:
  cpu: 2
  memory_gb: 4
  disk_size_gb: 10

entrypoint: uvicorn app.main:app --host 0.0.0.0 --port $PORT --limit-max-requests 1000 --timeout-keep-alive 300

# Cloud Runのリクエストサイズ制限を1000MBに設定
max_request_size: 1000m 